name: a
on:
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "hai from job1"
       echo "secret is {{ secrets.ONE }}"
       echo "added something"